#pragma once

//에너미 방향
enum ENEMYDIRECTION
{
	ENEMY_DIRECTION_LEFT_BOTTOM,
	ENEMY_DIRECTION_RIGHT_BOTTOM,
	ENEMY_DIRECTION_RIGHT_TOP,
	ENEMY_DIRECTION_LEFT_TOP
};
//에너미 상태
enum  ENEMYSTATE
{
	ENEMY_STATE_IDLE,
	ENEMY_STATE_MOVE,
	ENEMY_STATE_ATTACK,
	ENEMY_STATE_SKILL,
	ENEMY_STATE_SYNERGY_SKILL,
	ENEMY_STATE_DEAD,
};