#pragma once

//알프 방향
enum ALPHDIRECTION
{
	ALPH_DIRECTION_LEFT_BOTTOM,
	ALPH_DIRECTION_RIGHT_BOTTOM,
	ALPH_DIRECTION_RIGHT_TOP,
	ALPH_DIRECTION_LEFT_TOP
};
//알프 상태
enum  ALPHSTATE
{
	ALPH_STATE_IDLE,
	ALPH_STATE_MOVE,
	ALPH_STATE_ATTACK,
	ALPH_STATE_SKILL,
	ALPH_STATE_SYNERGY_SKILL,
	ALPH_STATE_DEAD,
};

//루시아 방향
enum  LUCIADIRECTION
{
	LUCIA_DIRECTION_LEFT_TOP,
	LUCIA_DIRECTION_LEFT_BOTTOM,
	LUCIA_DIRECTION_RIGHT_TOP,
	LUCIA_DIRECTION_RIGHT_BOTTOM
};
//루시아 상태
enum  LUCIASTATE
{
	LUCIA_STATE_IDLE,
	LUCIA_STATE_MOVE,
	LUCIA_STATE_ATTACK,
	LUCIA_STATE_SKILL,
	LUCIA_STATE_SYNERGY_SKILL,
	LUCIA_STATE_DEAD,
};